oraclejdk-8:
  build: oraclejdk-8
  container_name: oraclejdk-8
  command: "true"
  restart: "no"

server:
  build: server
  restart: always
  ports:
  - "8111:8111"
  volumes:
  - ./server/storage:/root/BuildServer

agent-alice:
  build: agent-alice
  restart: always
  links:
  - teamcity