version: '3.7'

services:
  jdk11:
    build: jdk11
    container_name: jdk11
    command: "true"
    restart: "no"

  server:
    build: server
    restart: always
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_storage:/root/BuildServer
    networks:
      - teamcity_network

  agent-alice:
    build: agent-alice
    restart: always
    networks:
      - teamcity_network

networks:
  teamcity_network:

volumes:
  teamcity_server_storage: