oraclejdk-8:
  build: oraclejdk-8
  container_name: oraclejdk-8
  command: "true"
  restart: "no"

teamcity:
  build: server
  restart: always
  ports:
  - "8111:8111"
  volumes:
  - ./server/storage:/root/BuildServer

teamcity-agent:
  build: alice
  restart: always
  links:
  - teamcity